appVersion: "latest"
image:
  app: ghcr.io/preparingforexams/telegram-horoscope-bot
openai:
  gptModel: gpt-3.5-turbo-0125
telegram:
  enabledChats:
    - "133399998"
    - "-1001725586482"
rateLimiter:
  # renovate: datasource=docker
  image: ghcr.io/preparingforexams/rate-limiter-migrations:4.2.1
