[tool.poetry]
name = "horoscopebot"
description = "Tells lies"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.10"
pendulum = "^2.0.0"
python-dotenv = "^0.20.0"
openai = "^0.18.0"
requests = "^2.0.0"
sentry-sdk = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "22.3.0"
flake8 = "4.0.1"
mypy = "0.942"
types-requests = "2.27.27"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
