[tool.poetry]
name = "horoscopebot"
description = "Tells lies"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[[tool.poetry.source]]
name = "internal"
url = "https://pypi.blindfolded.surgery"
priority = "explicit"

[tool.poetry.dependencies]
bs-config = { version = "0.1.1", extras = ["dotenv"], source = "internal" }
certifi = "2023.7.22"
Deprecated = "^1.2.13"
google-cloud-pubsub = "^2.0.0"
httpx = "^0.25.0"
openai = "^0.28.0"
pendulum = "^2.0.0"
python = "~3.11"
rate_limit = { version = "2.0.1", source = "internal" }
sentry-sdk = "^1.14.0"
tzdata = "2023.3"

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
mypy = "^1.4.0"
pytest = "^7.1.2"
ruff = "0.0.292"
types-Deprecated = "^1.2.9"
types-requests = "^2.31.0.1"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true

[tool.ruff]
extend-select = [
    "I001",
]

[tool.ruff.isort]
known-first-party = ["horoscopebot"]
