[tool.poetry]
name = "horoscopebot"
description = "Tells lies"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[[tool.poetry.source]]
name = "internal"
url = "https://pypi.bjoernpetersen.net"
priority = "explicit"

[tool.poetry.dependencies]
certifi = "2023.5.7"
Deprecated = "^1.2.13"
google-cloud-pubsub = "^2.0.0"
httpx = "^0.24.1"
openai = "^0.27.0"
pendulum = "^2.0.0"
python = "~3.11"
python-dotenv = "^1.0.0"
rate_limit = { version = "1.4.0", source = "internal" }
requests = "^2.28.2"
sentry-sdk = "^1.14.0"

[tool.poetry.dev-dependencies]
black = "^23.0.0"
flake8 = "^6.0.0"
mypy = "~1.4.0"
pytest = "^7.1.2"
types-Deprecated = "^1.2.9"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = "google.cloud.*"
ignore_missing_imports = true
