[tool.poetry]
name = "horoscopebot"
description = "Tells lies"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[tool.poetry.dependencies]
certifi = "2022.6.15"
openai = "^0.20.0"
pendulum = "^2.0.0"
python = "~3.10"
python-dotenv = "^0.20.0"
requests = "2.28.1"
sentry-sdk = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
mypy = "0.961"
types-requests = "2.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
