---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: horoscope
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: horoscope
  dataFrom:
    - find:
        path: "HOROSCOPE_"
      rewrite:
        - regexp:
            source: "HOROSCOPE_(.+)"
            target: "$1"
