apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
data:
  GSA_JSON: "{{ .Values.gcp.gsaJson }}"
stringData:
  OPENAI_TOKEN: "{{ .Values.openai.token }}"
  OTEL_EXPORTER_OTLP_TRACES_HEADERS: "x-honeycomb-team={{ .Values.honeycomb.team }}"
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  TELEGRAM_TOKEN: "{{ .Values.telegram.apiKey }}"
