apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: horoscope-secrets
  namespace: telegram-bots
data:
  GSA_JSON: "{{ .Values.gcp.gsaJson }}"
stringData:
  OPENAI_TOKEN: "{{ .Values.openai.token }}"
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  TELEGRAM_API_KEY: "{{ .Values.telegram.apiKey }}"
