---
apiVersion: v1
kind: Service
metadata:
  namespace: telegram-bots
  name: horoscope-update-handler
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: telegram-bots
  name: horoscope-update-handler
  labels:
    app: horoscope-update-handler
spec:
  revisionHistoryLimit: 1
  replicas: 1
  serviceName: horoscope-update-handler
  selector:
    matchLabels:
      app: horoscope-update-handler
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: telegram-bots
        name: horoscope-state
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: horoscope-update-handler
    spec:
      volumes:
        - name: service-account
          secret:
            secretName: horoscope-secrets
            items:
              - key: GSA_JSON
                path: ./gsa.json
      initContainers:
        - name: fix-volume-permissions
          image: alpine:3
          command:
            - chmod
            - -R
            - "777"
            - /state
          volumeMounts:
            - mountPath: /state
              name: horoscope-state
        - name: flyway
          image: ghcr.io/preparingforexams/rate-limiter-migrations:1.4.0
          args:
            - migrate
          volumeMounts:
            - mountPath: /state
              name: horoscope-state
          env:
            - name: FLYWAY_URL
              value: jdbc:sqlite:/state/usages.db
      containers:
        - name: app
          image: {{ .Values.image.app }}
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - mountPath: /state
              name: horoscope-state
            - mountPath: /gcp
              name: service-account
          env:
            - name: HOROSCOPE_MODE
              value: openai_chat
            - name: OPENAI_MODEL
              value: gpt-3.5-turbo
            - name: RATE_LIMIT_FILE
              value: /state/usages.db
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /gcp/gsa.json
          envFrom:
            - configMapRef:
                name: horoscope-telegram
            - configMapRef:
                name: horoscope-gcp
            - secretRef:
                name: horoscope-secrets
