---
apiVersion: v1
kind: Service
metadata:
  namespace: telegram-bots
  name: {{ .Release.Name }}-update-handler
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: telegram-bots
  name: {{ .Release.Name }}-update-handler
  labels:
    app: {{ .Release.Name }}-update-handler
spec:
  revisionHistoryLimit: 1
  replicas: 1
  serviceName: {{ .Release.Name }}-update-handler
  selector:
    matchLabels:
      app: {{ .Release.Name }}-update-handler
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: telegram-bots
        name: state
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-update-handler
    spec:
      volumes:
        - name: service-account
          secret:
            secretName: {{ .Release.Name }}
            items:
              - key: GSA_JSON
                path: ./gsa.json
      securityContext:
        fsGroup: 500
      initContainers:
        - name: flyway
          image: {{ .Values.rateLimiter.image }}
          args:
            - migrate
          volumeMounts:
            - mountPath: /state
              name: state
          env:
            - name: FLYWAY_URL
              value: jdbc:sqlite:/state/usages.db
      containers:
        - name: app
          image: {{ .Values.image.app }}
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - mountPath: /state
              name: state
            - mountPath: /gcp
              name: service-account
          env:
            - name: HOROSCOPE_MODE
              value: openai_chat
            - name: OPENAI_MODEL
              value: gpt-3.5-turbo-1106
            - name: RATE_LIMIT_FILE
              value: /state/usages.db
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /gcp/gsa.json
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-telegram
            - configMapRef:
                name: {{ .Release.Name }}-gcp
            - secretRef:
                name: {{ .Release.Name }}

